# Generated by Django 4.0.4 on 2022-05-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=300)),
                ('dir', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('num_habitacione', models.IntegerField()),
                ('check_in', models.CharField(max_length=10)),
                ('check_out', models.CharField(max_length=10)),
                ('imgs', models.ImageField(upload_to='')),
                ('id_dueño', models.IntegerField()),
                ('precio', models.CharField(max_length=10)),
                ('estatus', models.BooleanField()),
            ],
        ),
    ]
